// Generated by Wrangler by running `wrangler types`

interface Env {
  // Database
  MONGODB_URI: string;
  
  // Authentication
  SESSION_SECRET: string;
  JWT_SECRET: string;
  
  // Email (Resend)
  RESEND_API_KEY: string;
  
  // R2 Storage
  R2_BUCKET_NAME: string;
  R2_SECRET_ACCESS_KEY: string;
  R2_ACCESS_KEY_ID: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  R2_PUBLIC_DOMAIN: string;
  FILES_BUCKET: string; // Fallback bucket name
  
  // Application
  APP_URL: string;
  NODE_ENV: string;
}
